---
matrix:
  fast_finish: true
  include:
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.0 FUTURE_PARSER=yes
    - rvm: 2.1.9
      env: PUPPET_VERSION=4.0
    - rvm: 2.4.0
      env: PUPPET_VERSION=5.0
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
bundler_args: --without system_tests development
sudo: false
